Auth: Introduce Github OAuth2
ceph/pulpito pull request #77
Opened 2020-10-15 17:56 UTC by kamoltat

Enables the user to sign in using Github OAuth2,
using Beaker Middleware as a session plugin.
Only users that are in the Ceph community can
sign in and (In the future) have the priviledge to kill runs
or reschedule them and etc.

Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>

2020-10-30 12:57 UTC, kshtsk commented
I was trying to deploy this, and get while starting pulpito:
```Traceback (most recent call last):
  File "run.py", line 10, in <module>
    simpleapp_wsgi_app = deploy(prod_config)
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/deploy.py", line 9, in deploy
    return load_app(config)
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/core.py", line 218, in load_app
    app = module.app.setup_app(_runtime_conf, **kwargs)
  File "/home/pulpito/pulpito/pulpito/app.py", line 15, in setup_app
    **app_conf
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/__init__.py", line 86, in make_app
    app = Pecan(root, **kw)
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/core.py", line 844, in __init__
    super(Pecan, self).__init__(*args, **kw)
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/core.py", line 240, in __init__
    root = self.__translate_root__(root)
  File "/home/pulpito/pulpito/virtualenv/lib/python2.7/site-packages/pecan/core.py", line 275, in __translate_root__
    module = __import__(name, fromlist=fromlist)
  File "/home/pulpito/pulpito/pulpito/controllers/root.py", line 16, in <module>
    from pulpito.controllers.login import LoginController
  File "/home/pulpito/pulpito/pulpito/controllers/login.py", line 2, in <module>
    from requests_oauthlib import OAuth2Session
ImportError: No module named requests_oauthlib
```

2020-10-30 22:00 UTC, kshtsk commented
I guess you need to add `requests-oauthlib==1.3.0` to requirements.

2020-10-30 22:21 UTC, kshtsk requested changes
See comments.

2020-10-30 22:53 UTC, kshtsk commented
If I add those dependencies the pulpito is deploying okay. On the main page I can see "Login" linke, once I click it redirects me to the GitHub 404 error page and url: https://github.com/login/oauth/authorize?response_type=code&client_id=None&state=rhO2YihSf8PlloOXMAtsXWN4YGiDbo

2020-10-31 22:56 UTC, kshtsk commented
Rebase required

2020-11-30 14:07 UTC, kamoltat commented
@kshtsk you might have to include a .env file which has CLIENT_ID and CLIENT_SECRET. I'll send the file over to you through email

2020-11-30 14:08 UTC, kamoltat commented
> Rebase required

done!

2021-01-21 11:17 UTC, kshtsk commented
need to rebase

2021-06-29 23:43 UTC, zmc approved these changes
Aside from some very minor comments, I think this looks great.

2021-06-29 23:43 UTC, zmc commented on pulpito/app.py
> +from pecan import conf, make_app, request
Is this a mistake?

2021-06-29 23:43 UTC, zmc commented on pulpito/controllers/login.py
> +os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
Could this be done with the `.env` perhaps?

2023-05-15 14:47 UTC, kamoltat commented
Closing this PR, please refer to: https://github.com/VallariAg/teuthology-api/pull/5

2023-05-15 14:47 UTC, kamoltat commented
Closing this PR, please refer to: https://github.com/VallariAg/teuthology-api/pull/5

2023-05-15 14:47 UTC, closed without merging